CC=gcc
CFLAGS=-O -g
LIBS=-liup -lXm -lXmu -lXt -lX11 -lm
INCS=-I/tecgraf/iup/include

all: example1 example2 example3 example4 example5 example6 example7 example8

example1: example1.o 
	$(CC) $(CFLAGS) -o example1 example1.o $(LIBS)

example1.o: example1.c
	$(CC) -c example1.c $(INCS)

example2: example2.o 
	$(CC) $(CFLAGS) -o example2 example2.o $(LIBS)

example2.o: example2.c
	$(CC) -c example2.c $(INCS)

example3: example3.o 
	$(CC) $(CFLAGS) -o example3 example3.o $(LIBS)

example3.o: example3.c
	$(CC) -c example3.c $(INCS)

example4: example4.o 
	$(CC) $(CFLAGS) -o example4 example4.o $(LIBS)

example4.o: example4.c
	$(CC) -c example4.c $(INCS)

example5: example5.o 
	$(CC) $(CFLAGS) -o example5 example5.o $(LIBS)

example5.o: example5.c
	$(CC) -c example5.c $(INCS)

example6: example6.o 
	$(CC) $(CFLAGS) -o example6 example6.o $(LIBS)

example6.o: example6.c
	$(CC) -c example6.c $(INCS)

example7: example7.o 
	$(CC) $(CFLAGS) -o example7 example7.o $(LIBS)

example7.o: example7.c
	$(CC) -c example7.c $(INCS)

example8: example8.o 
	$(CC) $(CFLAGS) -o example8 example8.o $(LIBS)

example8.o: example8.c
	$(CC) -c example8.c $(INCS)
