CC=gcc
CFLAGS=-O -g
LIBS=-liupimglib -liup
INCS=-I../../../iup/include
LDIR=-L../../../iup/lib/$TEC_UNAME

all: example1 example2 example3 example4 example5 example6 example7 example8 example9 example10 example11 example12

example1: example1.o 
	$(CC) $(CFLAGS) -o example1 example1.o $(LIBS) $(LDIR)
example1.o: example1.c
	$(CC) -c example1.c $(INCS)

example2: example2.o 
	$(CC) $(CFLAGS) -o example2 example2.o $(LIBS) $(LDIR)
example2.o: example2.c
	$(CC) -c example2.c $(INCS)

example3: example3.o 
	$(CC) $(CFLAGS) -o example3 example3.o $(LIBS) $(LDIR)
example3.o: example3.c
	$(CC) -c example3.c $(INCS)

example4: example4.o 
	$(CC) $(CFLAGS) -o example4 example4.o $(LIBS) $(LDIR)
example4.o: example4.c
	$(CC) -c example4.c $(INCS)

example5: example5.o 
	$(CC) $(CFLAGS) -o example5 example5.o $(LIBS) $(LDIR)
example5.o: example5.c
	$(CC) -c example5.c $(INCS)

example6: example6.o 
	$(CC) $(CFLAGS) -o example6 example6.o $(LIBS) $(LDIR)
example6.o: example6.c
	$(CC) -c example6.c $(INCS)

example7: example7.o 
	$(CC) $(CFLAGS) -o example7 example7.o $(LIBS) $(LDIR)
example7.o: example7.c
	$(CC) -c example7.c $(INCS)

example8: example8.o 
	$(CC) $(CFLAGS) -o example8 example8.o $(LIBS) $(LDIR)
example8.o: example8.c
	$(CC) -c example8.c $(INCS)

example9: example9.o 
	$(CC) $(CFLAGS) -o example9 example9.o $(LIBS) $(LDIR)
example9.o: example9.c 
	$(CC) -c example9.c $(INCS)

example10: example10.o 
	$(CC) $(CFLAGS) -o example10 example10.o $(LIBS) $(LDIR)
example10.o: example10.c
	$(CC) -c example10.c $(INCS)

example11: example11.o 
	$(CC) $(CFLAGS) -o example11 example11.o $(LIBS) $(LDIR)
example11.o: example11.c
	$(CC) -c example11.c $(INCS)

example12: example12.o 
	$(CC) $(CFLAGS) -o example12 example12.o $(LIBS) $(LDIR)
example12.o: example12.c
	$(CC) -c example12.c $(INCS)
