
.PHONY: do_all iupcontrols iupimglib
do_all: iupcontrols iupimglib

iupcontrols:
	@$(MAKE) --no-print-directory -f ../tecmake_compact.mak 

iupimglib:
	@$(MAKE) --no-print-directory -f ../tecmake_compact.mak MF=iupimglib
