#!/bin/tcsh

foreach plat ( Linux26 Linux26_64 Linux26g4 Linux26g4_64 Linux32 Linux32_64 SunOS510 SunOS510x86 )
  echo $plat
  cp -f ../lib/$plat/*.so ../bin/$plat
  cp -f ../../cd/lib/$plat/*.so ../bin/$plat
  cp -f ../../im/lib/$plat/*.so ../bin/$plat
  cp -f ../../luagl/lib/$plat/*.so ../bin/$plat
  cp -f ../../lfs/lib/$plat/*.so ../bin/$plat
  rm -f ../bin/$plat/*3.so
end
