#!/bin/bash

Copy_SOs()
{
  PLAT=$1
  LUA_SFX=$2
  EXT=$3
  
  BASE_TEC=../..
  BASE_EXTRA=../..
#  BASE_TEC=~tecgraf/lib
#  BASE_EXTRA=~scuri/tecgraf
  
  echo $PLAT/Lua$LUA_SFX
  mkdir -p ../bin/$PLAT/Lua$LUA_SFX
  cp -f ../lib/$PLAT/*.$EXT ../bin/$PLAT/Lua$LUA_SFX
  cp -f $BASE_TEC/cd/lib/$PLAT/*.$EXT ../bin/$PLAT/Lua$LUA_SFX
  cp -f $BASE_TEC/im/lib/$PLAT/*.$EXT ../bin/$PLAT/Lua$LUA_SFX
  cp -f $BASE_TEC/lua$LUA_SFX/bin/$PLAT/lua$LUA_SFX ../bin/$PLAT/Lua$LUA_SFX
  cp -f $BASE_EXTRA/luagl/lib/$PLAT/*.$EXT ../bin/$PLAT/Lua$LUA_SFX
  cp -f $BASE_EXTRA/lfs/lib$LUA_SFX/$PLAT/*.$EXT ../bin/$PLAT/Lua$LUA_SFX
  
  #Remove Lua3 files if any
  rm -f ../bin/$PLAT/Lua$LUA_SFX/*3.$EXT 
  
  #Remove Lua5.X from Lua5.Y folder
  if [ $LUA_SFX == 5.1 ]; then
    rm -f ../bin/$PLAT/Lua$LUA_SFX/*52.$EXT 
  else
    rm -f ../bin/$PLAT/Lua$LUA_SFX/*51.$EXT 
  fi
  
  #Move the executable to the respective folder  
  mv -f ../bin/$PLAT/iuplua$LUA_SFX ../bin/$PLAT/Lua$LUA_SFX/iuplua$LUA_SFX
}

# Linux26g4 Linux26g4_64 Linux26g4_64co SunOS511x86 MacOS107

for plat in Linux32 Linux32_64 Linux35_64 Linux313_64
do
  Copy_SOs $plat 5.1 so
  Copy_SOs $plat 52 so
  if [ $plat == MacOS107 ]; then
    Copy_SOs $plat 5.1 dylib
    Copy_SOs $plat 52 dylib
  fi
done
