#!/bin/bash

Copy_DLLs()
{
  PLAT=$1
  SYS=$2
  LUA_SFX=$3
  
  if [ $SYS == Win64 ]; then
    SFX=_64
    PLAT=$PLAT$SFX
  fi
  
  echo $PLAT/$SYS/Lua$LUA_SFX
  mkdir ../bin/$SYS/Lua$LUA_SFX
  cp -f ../lib/$PLAT/*.dll ../bin/$SYS/Lua$LUA_SFX
  cp -f ../../cd/lib/$PLAT/*.dll ../bin/$SYS/Lua$LUA_SFX
  cp -f ../../im/lib/$PLAT/*.dll ../bin/$SYS/Lua$LUA_SFX
  cp -f ../../lua$LUA_SFX/lib/$PLAT/*.dll ../bin/$SYS/Lua$LUA_SFX
  cp -f ../../luagl/lib$LUA_SFX/$PLAT/*.dll ../bin/$SYS/Lua$LUA_SFX
  cp -f ../../lfs/lib$LUA_SFX/$PLAT/*.dll ../bin/$SYS/Lua$LUA_SFX
  
  if [ $1 == dll8 ]; then
    cp -frv ../../lua$LUA_SFX/bin/$SYS/Microsoft.VC80.CRT ../bin/$SYS/Lua$LUA_SFX
  fi
  if [ $1 == dll10 ]; then
    cp -f ../dist/Microsoft.VC100.CRT/$PLAT/* ../bin/$SYS/Lua$LUA_SFX
  fi
  
  rm -f ../bin/$SYS/Lua$LUA_SFX/*3.dll
  if [ $LUA_SFX == 5.1 ]; then
    rm -f ../bin/$SYS/Lua$LUA_SFX/*52.dll
  else
    rm -f ../bin/$SYS/Lua$LUA_SFX/*51.dll
  fi
  
  mv -f ../bin/$SYS/iuplua$LUA_SFX.exe ../bin/$SYS/Lua$LUA_SFX/iuplua$LUA_SFX.exe
}

Copy_DLLs dll8 Win32 5.1
Copy_DLLs dll8 Win64 5.1
Copy_DLLs dll10 Win32 52
Copy_DLLs dll10 Win64 52

Copy_DLLs cygw17 cygw17 5.1
Copy_DLLs cygw17 cygw17 52
