#!/bin/tcsh

foreach plat ( MacOS107 )
  echo $plat
  cp -f ../lib/$plat/*.so ../lib/$plat/*.dylib ../bin/$plat
  cp -f ../../cd/lib/$plat/*.so ../../cd/lib/$plat/*.dylib ../bin/$plat
  cp -f ../../im/lib/$plat/*.so ../../im/lib/$plat/*.dylib ../bin/$plat
  cp -f ../../luagl/lib/$plat/*.so ../../luagl/lib/$plat/*.dylib ../bin/$plat
  cp -f ../../lfs/lib/$plat/*.so ../../lfs/lib/$plat/*.dylib ../bin/$plat
  rm -f ../bin/$plat/*3.so ../bin/$plat/*3.dylib
end
