
.PHONY: do_all iuplua5 iuplua3
do_all: iuplua5 iuplua3

iuplua5:
	@$(MAKE) --no-print-directory -f ../tecmake_compact.mak 

iuplua3:
	@$(MAKE) --no-print-directory -f ../tecmake_compact.mak MF=iuplua3
