
.PHONY: do_all iuplua5 iuplua5gtk iuplua3
do_all: iuplua5

iuplua5:
	@$(MAKE) --no-print-directory -f ../tecmake.mak 

iuplua5gtk:
	@$(MAKE) --no-print-directory -f ../tecmake.mak USE_GTK=Yes

iuplua3:
	@$(MAKE) --no-print-directory -f ../tecmake.mak MF=iuplua3
